defaults: &defaults
  ftp_host:             localhost
  ftp_login:            ftpuser
  ftp_password:         ftpuserpw
  ftp_filename:         patents.csv
  downloader_class:     FtpDownloader

development:
  <<: *defaults
  ftp_path:             /data/dev

test:
  <<: *defaults
  ftp_path:             /data/test

production:
  <<: *defaults
  ftp_path:             /data/prod
